CREATE TABLE produtos (
 id VARCHAR(50) PRIMARY KEY, nome VARCHAR(150) NOT NULL,
 preco NUMERIC(10,2) NOT NULL DEFAULT 0.00, custo NUMERIC(10,2) NOT NULL DEFAULT 0.00,
 fornecedor VARCHAR(150), quantidade_inicial INTEGER NOT NULL DEFAULT 0,
 estoque_minimo INTEGER NOT NULL DEFAULT 5, data_cadastro TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 data_atualizacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 CONSTRAINT chk_produto_quantidade CHECK(quantidade_inicial>=0),
 CONSTRAINT chk_produto_estoque_minimo CHECK(estoque_minimo>=0),
 CONSTRAINT chk_produto_preco CHECK(preco>=0), CONSTRAINT chk_produto_custo CHECK(custo>=0)
);
CREATE TABLE movimentacao (
 id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 codigo_barras VARCHAR(50) NOT NULL REFERENCES produtos(id) ON UPDATE CASCADE ON DELETE RESTRICT,
 quantidade INTEGER NOT NULL CHECK(quantidade>0),
 tipo VARCHAR(7) NOT NULL CHECK(tipo IN ('ENTRADA','SAIDA')),
 observacao VARCHAR(255), data_movimentacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE OR REPLACE FUNCTION atualizar_data_produto() RETURNS TRIGGER AS $$
BEGIN NEW.data_atualizacao=CURRENT_TIMESTAMP; RETURN NEW; END; $$ LANGUAGE plpgsql;
CREATE TRIGGER trg_produtos_data_atualizacao BEFORE UPDATE ON produtos
FOR EACH ROW EXECUTE FUNCTION atualizar_data_produto();
CREATE INDEX idx_movimentacao_codigo_barras ON movimentacao(codigo_barras);
CREATE INDEX idx_movimentacao_data ON movimentacao(data_movimentacao DESC);
